apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  name: system:openshift:scc:nonroot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot
subjects:
- kind: ServiceAccount
  name: {{ include "clickhouse.name" . }}
  namespace: {{ .Release.Namespace }}
