apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodetest-pvc
  namespace: nodetest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""