apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nodetest
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: externalDiskVG
provisioner: topolvm.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true