{{/*
TLS helpers.

global.tls.mode:
  auto        - certificates are generated by Helm and signed by a CA (default).
                The CA comes from the Secret "<prefix>-ca" (tls.crt/tls.key), which
                install.sh creates so that all components share a single CA. Without it,
                each chart generates and keeps its own CA ("<prefix>-<component>-ca").
                Certificates are reused on upgrade unless global.tls.regenerate=true.
  existing    - the admin provides Secrets with tls.crt, tls.key and ca.crt.
  certManager - cert-manager Certificates are created from global.tls.certManager.issuer*.

Every TLS Secret contains tls.crt, tls.key and ca.crt, whatever the mode.
*/}}

{{- define "common.tls.mode" -}}
{{- $mode := .Values.global.tls.mode | default "auto" -}}
{{- if not (has $mode (list "auto" "existing" "certManager")) -}}
{{- fail (printf "global.tls.mode must be one of auto, existing, certManager (got %q)" $mode) -}}
{{- end -}}
{{- $mode -}}
{{- end -}}

{{/*
Name of the TLS Secret to mount.
Usage: include "common.tls.secretName" (dict "ctx" $ "component" "kafka" "existingSecret" .Values.kafka.tls.existingSecret)
*/}}
{{- define "common.tls.secretName" -}}
{{- if eq (include "common.tls.mode" .ctx) "existing" -}}
{{- required (printf "global.tls.mode=existing requires the name of an existing Secret (tls.crt, tls.key, ca.crt) for %q" .component) .existingSecret -}}
{{- else -}}
{{- include "common.fullname" (dict "ctx" .ctx "component" (printf "%s-tls" .component)) -}}
{{- end -}}
{{- end -}}

{{/*
Loads the signing CA into the render cache (key "ca").
Pass the chart's main component so that one chart uses one CA.
Usage: include "common.tls.loadCA" (dict "ctx" $ "component" "kafka")
*/}}
{{- define "common.tls.loadCA" -}}
{{- include "common.cache" .ctx -}}
{{- $cache := index .ctx.Values "__cmCache" -}}
{{- if not (hasKey $cache "ca") -}}
{{- $shared := .ctx.Values.global.tls.caSecret | default (printf "%s-ca" (include "common.prefix" .ctx)) -}}
{{- $own := include "common.fullname" (dict "ctx" .ctx "component" (printf "%s-ca" .component)) -}}
{{- $s := lookup "v1" "Secret" .ctx.Release.Namespace $shared -}}
{{- if and $s $s.data (hasKey $s.data "tls.crt") (hasKey $s.data "tls.key") -}}
{{- $_ := set $cache "ca" (buildCustomCert (index $s.data "tls.crt") (index $s.data "tls.key")) -}}
{{- else -}}
{{- $o := lookup "v1" "Secret" .ctx.Release.Namespace $own -}}
{{- if and $o $o.data (hasKey $o.data "tls.crt") (hasKey $o.data "tls.key") -}}
{{- $_ := set $cache "ca" (buildCustomCert (index $o.data "tls.crt") (index $o.data "tls.key")) -}}
{{- else -}}
{{- $_ := set $cache "ca" (genCA (printf "%s CM MES dependencies CA" (include "common.prefix" .ctx)) 3650) -}}
{{- end -}}
{{- $_ := set $cache "caOwnedName" $own -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Chart-owned CA Secret, rendered only in auto mode when the shared "<prefix>-ca" Secret
does not exist. Every chart must include this once (tls.yaml).
Usage: include "common.tls.caSecret" (dict "ctx" $ "component" "kafka")
*/}}
{{- define "common.tls.caSecret" -}}
{{- if eq (include "common.tls.mode" .ctx) "auto" -}}
{{- include "common.tls.loadCA" . -}}
{{- $cache := index .ctx.Values "__cmCache" -}}
{{- if hasKey $cache "caOwnedName" -}}
{{- $ca := index $cache "ca" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $cache "caOwnedName" }}
  namespace: {{ .ctx.Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "ctx" .ctx "component" .component) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ $ca.Cert | b64enc }}
  tls.key: {{ $ca.Key | b64enc }}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Server or client certificate: a Secret (auto), a cert-manager Certificate
(certManager) or nothing (existing).
  name      - Secret name (from common.tls.secretName)
  component - chart main component (selects the CA and the labels)
  cn        - common name
  dnsNames  - list of DNS SANs (optional for client certificates)
  pkcs8     - true to store the key as PKCS#8 ("BEGIN PRIVATE KEY"), required by Kafka
Usage: include "common.tls.certificate" (dict "ctx" $ "component" "kafka" "name" $secret "cn" "cmmes-kafka" "dnsNames" $dns "pkcs8" true)
*/}}
{{- define "common.tls.certificate" -}}
{{- $mode := include "common.tls.mode" .ctx -}}
{{- $tls := .ctx.Values.global.tls -}}
{{- if eq $mode "auto" -}}
{{- $crt := "" -}}
{{- $key := "" -}}
{{- $caCrt := "" -}}
{{- $existing := lookup "v1" "Secret" .ctx.Release.Namespace .name -}}
{{- if and $existing $existing.data (hasKey $existing.data "tls.crt") (hasKey $existing.data "ca.crt") (not $tls.regenerate) -}}
{{- $crt = index $existing.data "tls.crt" | b64dec -}}
{{- $key = index $existing.data "tls.key" | b64dec -}}
{{- $caCrt = index $existing.data "ca.crt" | b64dec -}}
{{- else -}}
{{- include "common.tls.loadCA" (dict "ctx" .ctx "component" .component) -}}
{{- $ca := index .ctx.Values.__cmCache "ca" -}}
{{- $cert := genSignedCert .cn (.ips | default (list)) (.dnsNames | default (list)) (int ($tls.validityDays | default 1825)) $ca -}}
{{- $crt = $cert.Cert -}}
{{- $key = $cert.Key -}}
{{- $caCrt = $ca.Cert -}}
{{- end -}}
{{- if .pkcs8 -}}
{{- $key = include "common.tls.pkcs8" $key -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .ctx.Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "ctx" .ctx "component" .component) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $crt | b64enc }}
  tls.key: {{ $key | b64enc }}
  ca.crt: {{ $caCrt | b64enc }}
{{- else if eq $mode "certManager" -}}
{{- $cm := $tls.certManager | default dict -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .ctx.Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "ctx" .ctx "component" .component) | nindent 4 }}
spec:
  secretName: {{ .name }}
  commonName: {{ .cn | quote }}
  {{- with .dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  duration: {{ $cm.duration | default "8760h" }}
  renewBefore: {{ $cm.renewBefore | default "720h" }}
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: {{ required "global.tls.mode=certManager requires global.tls.certManager.issuerName" $cm.issuerName | quote }}
    kind: {{ $cm.issuerKind | default "ClusterIssuer" }}
    group: {{ $cm.issuerGroup | default "cert-manager.io" }}
{{- end -}}
{{- end -}}

{{/*
Converts an RSA PKCS#1 PEM key ("BEGIN RSA PRIVATE KEY", as produced by Sprig) to
PKCS#8 ("BEGIN PRIVATE KEY"), which Kafka requires for PEM keystores.
Keys that are already PKCS#8 are returned unchanged.
The PKCS#8 wrapper is: SEQUENCE { INTEGER 0, SEQUENCE { rsaEncryption OID, NULL }, OCTET STRING <pkcs1> }
Usage: include "common.tls.pkcs8" $pem
*/}}
{{- define "common.tls.pkcs8" -}}
{{- if contains "BEGIN RSA PRIVATE KEY" . -}}
{{- $body := . | replace "-----BEGIN RSA PRIVATE KEY-----" "" | replace "-----END RSA PRIVATE KEY-----" "" | nospace -}}
{{- $der := b64dec $body -}}
{{- $len := len $der -}}
{{- if or (lt $len 256) (gt $len 65000) -}}
{{- fail "common.tls.pkcs8: unsupported RSA key size" -}}
{{- end -}}
{{- $total := add $len 22 -}}
{{- $head := printf "\x30\x82%s%s" (include "common.tls.byte" (div $total 256)) (include "common.tls.byte" (mod $total 256)) -}}
{{- $alg := "\x02\x01\x00\x30\x0d\x06\x09\x2a\x86\x48\x86\xf7\x0d\x01\x01\x01\x05\x00" -}}
{{- $octet := printf "\x04\x82%s%s" (include "common.tls.byte" (div $len 256)) (include "common.tls.byte" (mod $len 256)) -}}
{{- $b64 := printf "%s%s%s%s" $head $alg $octet $der | b64enc -}}
-----BEGIN PRIVATE KEY-----
{{ regexFindAll ".{1,64}" $b64 -1 | join "\n" }}
-----END PRIVATE KEY-----
{{ else -}}
{{- . -}}
{{- end -}}
{{- end -}}

{{/* One raw byte (0-255), built by decoding a one-byte base64 string. */}}
{{- define "common.tls.byte" -}}
{{- $alphabet := "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" -}}
{{- $b := int . -}}
{{- $i1 := int (div $b 4) -}}
{{- $i2 := int (mul (mod $b 4) 16) -}}
{{- printf "%s%s==" (substr $i1 (int (add $i1 1)) $alphabet) (substr $i2 (int (add $i2 1)) $alphabet) | b64dec -}}
{{- end -}}
