name = "microshift"
description = "demo-microshift-embedded"
version = "0.0.1"
modules = []
groups = []
distro = ""

[[packages]]
name = "microshift"
version = "*"

[[packages]]
name = "autofs"
version = "*"

[[packages]]
name = "workload-manifests"
version = "*"

[[packages]]
name = "gdm"
version = "*" 


[[packages]]
name = "firefox"
version = "*"

[customizations]

[[customizations.user]]
name = "admin"
description = "Admin user"
password = "$6$aX6HWT.Voy4x9byR$AHNts/pKEzNLnU6bb88Bbq52fWGYpPpXgZPFztb7ayMHkfFCkPq/NBlxBBstA9yGJPudj1unB0NFHYQ6fRKbd1"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzR2ixpaJIecsCunvgJjg18NEFPPTYKewSa9eD6GMptHNYyybIqYtng/2/AsNSZ9cp54fCqt5QUIsD7OfFJQnN7/1z7sHyeEM5t2PhK1GOykq2klga//HlvCgK3DJTy9az+wq5JVyHLUZnRGtgOQRgYLox2CadThBs2aM8QwSXCDjhIjgApwEvoFuH9yRFAervBNykvIiEx+K8p1w2vkntCn8XsiuZ4xRwNuttiudysCHYq9EkdOHIEt6a+ktR7cxpD8uAoxym4UitoHynCy6Jp7Ji0GNaVNhsE9dkcXjQDmP7s+IRs7s83Om4dDpXzhTAol9++MvHsDjYtEUN5Se/N44jjwyeVXivzF7IjZg1WHJgb1gYiYRUoBhzcqzO8Vft9xdjpS8sZ/46+CQA2XPEw5uxP5iBFHgmzbOYl2GPMr67qK19gtAduXvofSMDiXGkzIPQoXn6xnQjl6QHrn/uCk1q4+76jqYZcRzGj0NNMx4Viu+zws9GLMK9M7arym8= larizmen@hal9k"
groups = ["users", "wheel"]


[customizations.services]
enabled = ["microshift"]

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d7a26cf7bc38061639ee3b8515bc2a8cb8c64f5ebbb70250dd43e633222cb19c"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6b38d75b297fa52d1ba29af0715cec2430cd5fda1a608ed0841a09c55c292fb3"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:68c513e4be3224c418e14e665ad79fdaef130f67d8aceb365921be8fb2b9c209"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b3cc4a7529a6c70b983803c59ee744c5a0a989ca6f8c6eab15d041d96399df88"

[[containers]]
source = "registry.access.redhat.com/ubi8/openssl@sha256:9e743d947be073808f7f1750a791a3dbd81e694e37161e8c6c6057c2c342d671"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f9125d62134690c8bf662df73fdd09fb89a439ecec4f653c6fdde9f822d93599"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7430c24e583c8558ba1c913bc7500628145bb5d3fc783e3d5bf669c25abc43cb"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8b27a584c2fd72a69c83f0803207821aedf97cb3a92c5e1e8cbc849218093a98"

[[containers]]
source = "registry.redhat.io/lvms4/topolvm-rhel9@sha256:d0c039eba8157965b0a7971ad4e01576d2c1e31b09fe938554163b324cc4dc73"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:caa0bbab808d8cbed476e8fa3e296ceb90f8d7d253e36588fa77e639ea389d55"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-livenessprobe@sha256:829a8e4d34404abbd22fddb6ebfa0f74daa55f2697fb147da77b83fc8b473d8c"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-external-resizer@sha256:7ee0257998b7f804fcde9c095b4dc240c510eb316d7223e8485f701b5c9f2fbf"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-external-provisioner@sha256:b453a5c76ba4e975a978e31a51531b1d6233723b0d944622caf7844dedf9ad5a"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:84536df7c4cc304d447d134a9e5c891d10da3feb35244f0f66b772129c63c7af"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8efe85af899e0e92150a169ad9557b041b1dc06715ba1279b28f8ab28121c7ee"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8c401faae75e521816b940c35288a5b9684422856ea897336f356ea8e2d3b334"
