---
- name: "Create MicroShift embedded image"
  hosts: image_builder
  become: true
  gather_facts: true
  vars_files:
  - ../vars/main.yml
  tasks:

######### Add Microshift repo sources
        - name: Create rhocp-{{ microshift_release }}.toml configuration file
          copy:
            dest: "/tmp/rhocp-{{ microshift_release }}.toml"
            content: |
              id = "rhocp-{{ microshift_release }}"
              name = "Red Hat OpenShift Container Platform {{ microshift_release }} for RHEL 9"
              type = "yum-baseurl"
              url = "https://cdn.redhat.com/content/dist/layered/rhel9/{{ ansible_architecture }}/rhocp/{{ microshift_release }}/os"
              check_gpg = true
              check_ssl = true
              system = false
              rhsm = true

        - name: Create fast-datapath.toml configuration file
          copy:
            dest: "/tmp/fast-datapath.toml"
            content: |
              id = "fast-datapath"
              name = "Fast Datapath for RHEL 9"
              type = "yum-baseurl"
              url = "https://cdn.redhat.com/content/dist/layered/rhel9/{{ ansible_architecture }}/fast-datapath/os"
              check_gpg = true
              check_ssl = true
              system = false
              rhsm = true

        - name: Add sources to Image Builder
          command: "sudo composer-cli sources add {{ item }}"
          loop:
            - "/tmp/rhocp-{{ microshift_release }}.toml"
            - "/tmp/fast-datapath.toml"
#########


######### Get Microshift container images to be embedded


        - name: Get microshift offline images
          when: microshift_embedded_images is defined and microshift_embedded_images is true
          block: 
          - name: Enable OCP repo on the host for Microshift
            community.general.rhsm_repository:
              state: enabled
              name: "rhocp-{{ microshift_release }}-for-rhel-9-{{ ansible_architecture }}-rpms"

          - name: Getting microshift-release-info package
            ansible.builtin.shell:
              cmd: dnf download -y microshift-release-info
            register: _dnf_output

            #bug with cmd output
          - name: Getting microshift-release-info package
            ansible.builtin.shell:
              cmd: dnf download -y microshift-release-info
            register: _dnf_output

          - name: Capture filename from the output
            set_fact:
              _microshift_release_info_string: >-
                {{
                  _dnf_output.stdout
                  | regex_search('microshift-release-info-[^\n:]*')
                  | default('')
                  | regex_replace(':$', '')
                }}

          - name: Display captured microshift-release-info string
            debug:
              var: _microshift_release_info_string

          - name: Running rpm2cpio for the microshift-release-info package
            ansible.builtin.shell:
              cmd: rpm2cpio {{ _microshift_release_info_string }} | cpio -idmv

          - name: Be sure that jq is installed
            ansible.builtin.dnf:
              name: jq

          - name: Clear previous Microshift images
            ansible.builtin.file:
              path: /root/blueprint-microshift-embedded.toml
              state: absent
  
          - name: Extracting the Microshift images
            ansible.builtin.shell:
              cmd: jq -r '.images | .[] | ("[[containers]]\nsource = \"" + . + "\"\n")' "./usr/share/microshift/release/release-{{ ansible_architecture }}.json" >> "/root/blueprint-microshift-embedded.toml"

          # This repo is just to download microshift_release_info
          - name: Disable OCP repo 
            community.general.rhsm_repository:
              state: disabled
              name: "rhocp-{{ microshift_release }}-for-rhel-9-{{ ansible_architecture }}-rpms"
#########



######### Include pull-secret in Image Builder

        - name: Add pull-secret to Image Builder
          when: microshift_embedded_images | default(false) == true
          block:
          - name: Include secrets file with pull-secret if microshift_embedded_images is true
            include_vars:
              file: "../vars/secrets.yml"
          - name: Create /etc/osbuild-worker/ directory
            file:
              path: /etc/osbuild-worker/
              state: directory

          - name: Put pull_secret into /etc/osbuild-worker/pull-secret.json
            copy:
              content: "{{ microshift_pull_secret }}"
              dest: /etc/osbuild-worker/pull-secret.json

          - name: Create /etc/osbuild-worker/osbuild-worker.toml
            copy:
              content: |
                [containers]
                auth_file_path = "/etc/osbuild-worker/pull-secret.json"
              dest: /etc/osbuild-worker/osbuild-worker.toml

          - name: Restart osbuild-worker@1.service
            systemd:
              name: osbuild-worker@1
              state: restarted
######### 
