---
- name: "Create MicroShift embedded image"
  hosts: image_builder
  become: true
  gather_facts: true
  vars_files:
  - ../vars/main.yml

- ansible.builtin.import_playbook: 00_image_builder_prepare.yml

- ansible.builtin.import_playbook: 02_image_builder_microshift_prepare.yml

- ansible.builtin.import_playbook: 03_generate_rpm_manifests.yml
  when: microshift_embedded_manifests|default(false) 

- ansible.builtin.import_playbook: 05_generate_blueprint.yml
  when: microshift_embedded_generate_blueprint|default(false) 

- ansible.builtin.import_playbook: 10_image_builder_create.yml

