apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "ctx" $ "component" "otel") | nindent 4 }}
  {{- with (dig "service" "annotations" dict .Values.observability) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" (dict "ctx" $ "component" "otel") | nindent 4 }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
      appProtocol: http
