# Default values for clickhouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: clickhouse/clickhouse-server:24.2
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   memory: 6Gi
  # requests:
  #   cpu: 200m
  #   memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

# Service
service:
  name: clickhouse
  type: ClusterIP
  nativetls:
    port: 9440
    name: nativetls
  https:
    port: 8443
    name: https

# Route
ingress:
  enabled: false
  name: clickhouse
  hostSuffix: <cluster suffix>

# Volumes
clickhouseData:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  pvcName: clickhouse-data
  volumeName: ""

clickhouseLog:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  pvcName: clickhouse-log
  volumeName: ""

# Config maps
usersConfig:
  name: users
  defaultPassword: <Clickhouse default user password>

clickhouseConfig:
  name: config
  openSSL:
    validateCertificates: false
    invalidCertificateHandler: AcceptCertificateHandler

clickhouse:
  secretName: clickhouse-secrets
  tls:
    autoGenerated: true
    caCertificate: ""
    serverCertificate: ""
    serverKey: ""